CC = gcc
ICS = ..
CFLAGS = -Wall -O2

PROGS = sumarrayrows\
	sumarraycols\
	sumarray3d\

all: $(PROGS)

mountaintarfile:
	tar cvf - mountain > mountain.tar

matmulttarfile:
	tar cvf - matmult > matmult.tar

clean:
	rm -f $(PROGS) *.o *~


